## Week 1 Homework for Machine Learning Zoocamp

In [1]:
# install libraries
import numpy as np
import pandas as pd

## Question 1

What's the version of NumPy that you installed?

You can get the version information using the __version__ field:

In [2]:
np.__version__

'1.22.3'

### Getting the data 

For this homework, we'll use the Car price dataset. Download it from here.

You can do it with wget:

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-08 06:08:05--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv.3’

data.csv.3          100%[===================>]   1.41M  5.68MB/s    in 0.2s    

2022-09-08 06:08:06 (5.68 MB/s) - ‘data.csv.3’ saved [1475504/1475504]



## Question 2

How many records are in the dataset? Here you need to specify the number of rows.

* 16 
* 6572 
* 11914 
* 18990 


In [4]:
df = pd.read_csv("data.csv")
df.head(n=2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

In [5]:
df.shape   # Answer: There are 11914 records in the dataset.

(11914, 16)

## Question 3 

Who are the most frequent car manufacturers (top-3) according to the dataset?

* Chevrolet, Volkswagen, Toyota
* Chevrolet, Ford, Toyota
* Ford, Volkswagen, Toyota
* Chevrolet, Ford, Volkswagen

Note: You should rely on "Make" column in this question.

In [6]:
df.Make.value_counts().head()  # Answer: Chevrolet, Ford, Volkswagen

Chevrolet     1123
Ford           881
Volkswagen     809
Toyota         746
Dodge          626
Name: Make, dtype: int64

## Question 4

What's the number of unique Audi car models in the dataset?

* 3
* 16
* 26
* 34

In [7]:
df[ df.Make == "Audi" ].Model.nunique()  # Answer: There are 34 unique Audi car models.

34

## Question 5

How many columns in the dataset have missing values?

* 5
* 6
* 7
* 8


In [8]:
# Answer: 5 columns have missing values
cols_with_na = [ col for col in df.columns if df[col].isna().any() ]
cols_with_na

['Engine Fuel Type',
 'Engine HP',
 'Engine Cylinders',
 'Number of Doors',
 'Market Category']

## Question 6

Find the median value of "Engine Cylinders" column in the dataset.  
Next, calculate the most frequent value of the same "Engine Cylinders".  
Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.  
Now, calculate the median value of "Engine Cylinders" once again.  
Has it changed?  

Hint: refer to existing mode and median functions to complete the task.

* Yes
* No

In [9]:
# Find the median and mode
median = df['Engine Cylinders'].median()
mode = df['Engine Cylinders'].mode()[0]
print(f"Median: {median}")
print(f"Mode: {mode}")

Median: 6.0
Mode: 4.0


In [10]:
# Fill missing values with the mode.
df['Engine Cylinders'].fillna(mode, inplace=True)

In [11]:
# Find the median of the filled column. Answer: No, the median has not changed.
df['Engine Cylinders'].median()

6.0

In [12]:
# Check that the column does not have missing values.
df['Engine Cylinders'].isna().any()

False

## Question 7

Select all the "Lotus" cars from the dataset.  

Select only columns "Engine HP", "Engine Cylinders".  

Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).  

Get the underlying NumPy array. Let's call it X.  

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.  

Invert XTX.  

Create an array y with values \[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800\].  


Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.  

What's the value of the first element of w?  

Note: You just implemented linear regression. We'll talk about it in the next lesson.

* -0.0723
* 4.5949
* 31.6537
* 63.5643

In [13]:
# Select Lotus cars and only columns "Engine HP", "Engine Cylinders".
lotus_df = df[ df.Make == "Lotus" ][ ["Engine HP", "Engine Cylinders"]]
lotus_df.head()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

In [14]:
lotus_df.shape

(29, 2)

In [15]:
# Remove duplicate rows, and check that only 9 rows should remain
lotus_df_nodup = lotus_df.drop_duplicates(ignore_index=True)
lotus_df_nodup

Engine HP  Engine Cylinders
0      189.0               4.0
1      218.0               4.0
2      217.0               4.0
3      350.0               8.0
4      400.0               6.0
5      276.0               6.0
6      345.0               6.0
7      257.0               4.0
8      240.0               4.0

In [16]:
# Get the numpy array of the dataframe
X = lotus_df_nodup.to_numpy()
X.shape

(9, 2)

In [17]:
# Show the transpose of X.
X.T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [18]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [19]:
# Multiply X transpose with X.
XTX = X.T.dot(X)

In [20]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [21]:
# Compute the inverse of XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [22]:
# Create the y array.
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [23]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# What's the value of the first element of w?  Answer: First element of w is 4.5949.

w = XTX_inv.dot(X.T).dot(y)
w

array([  4.59494481, -63.56432501])

## Checking the Coefficients of the Linear Regression in Q7

In the following section, I run scikit-learn's LinearRegression and fit a model on (X, y) from Question 7, and compare the coefficients.  I find out that in Q7, we did not add a column of 1's to matrix X, which means we did not fit an intercept in the model.  Hence, for scikit-learn regression, I set the parameter _fit_intercept_ to False.  The resulting model shows coefficients which tally with the coefficients we computed in Q7.

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
lr = LinearRegression(fit_intercept=False)
lr.fit(X, y)

LinearRegression(fit_intercept=False)

In [26]:
lr.coef_

array([  4.59494481, -63.56432501])

In [27]:
lr.predict(X)

array([ 614.18726905,  747.44066855,  742.84572374, 1099.71608343,
       1456.59197396,  886.81881751, 1203.8700094 ,  926.64351614,
        848.52945437])

In [28]:
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])